on:
  workflow_call:
    outputs:
      version:
        description: The version number that all buildpacks are set to
        value: ${{ jobs.release-detect.outputs.version }}
      buildpacks:
        description: The list of {buildpack_id, buildpack_version, buildpack_dir, buildpack_artifact_prefix, docker_repository} values for a buildpack formatted as a JSON array
        value: ${{ jobs.release-detect.outputs.buildpacks }}

jobs:
  release-detect:
    name: Executing
    runs-on: ubuntu-latest
    outputs:
      buildpacks: ${{ steps.generate-buildpack-matrix.outputs.buildpacks }}
      version: ${{ steps.generate-buildpack-matrix.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Buildpack Matrix
        id: generate-buildpack-matrix
        uses: heroku/languages-github-actions/.github/actions/generate-buildpack-matrix@main
